// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Analytic struct {
	ID          int32              `json:"id"`
	UrlID       pgtype.Int4        `json:"url_id"`
	VisitorIp   pgtype.Text        `json:"visitor_ip"`
	UserAgent   pgtype.Text        `json:"user_agent"`
	Referer     pgtype.Text        `json:"referer"`
	Timestamp   pgtype.Timestamptz `json:"timestamp"`
	CountryCode pgtype.Text        `json:"country_code"`
	DeviceType  pgtype.Text        `json:"device_type"`
}

type CustomDomain struct {
	ID        int32              `json:"id"`
	Domain    string             `json:"domain"`
	UserID    string             `json:"user_id"`
	Verified  pgtype.Bool        `json:"verified"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Tag struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Url struct {
	ID          int32              `json:"id"`
	OriginalUrl string             `json:"original_url"`
	ShortCode   string             `json:"short_code"`
	UserID      pgtype.Text        `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	ClickCount  pgtype.Int4        `json:"click_count"`
	IsActive    pgtype.Bool        `json:"is_active"`
}

type UrlTag struct {
	UrlID int32 `json:"url_id"`
	TagID int32 `json:"tag_id"`
}
