// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddURLTag(ctx context.Context, arg AddURLTagParams) error
	CreateAnalytics(ctx context.Context, arg CreateAnalyticsParams) (Analytic, error)
	CreateURL(ctx context.Context, arg CreateURLParams) (Url, error)
	DeactivateURL(ctx context.Context, arg DeactivateURLParams) error
	GetAnalyticsByURLID(ctx context.Context, urlID pgtype.Int4) ([]Analytic, error)
	GetURLByShortCode(ctx context.Context, shortCode string) (Url, error)
	GetURLTags(ctx context.Context, urlID int32) ([]Tag, error)
	GetURLsByUserID(ctx context.Context, userID pgtype.Text) ([]Url, error)
	IncrementClickCount(ctx context.Context, id int32) (pgtype.Int4, error)
}

var _ Querier = (*Queries)(nil)
