# fly.toml app configuration file generated for snax-url-shortener on 2025-05-28T16:05:11+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "snax-url-shortener"
primary_region = "sin"

[build]
  dockerfile = "url-shortener/Dockerfile"
  context = "."

[env]
  ENV = "production"
  PORT = "8080"
  SERVICE_NAME = "url-shortener"

# Add your sensitive environment variables using `fly secrets set`:
# fly secrets set NEON_DATABASE_URL="your-database-url"
# fly secrets set CLERK_SECRET_KEY="your-clerk-key"
# fly secrets set REDIS_URL="your-redis-url"
# etc...

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "30s"
  interval = "15s"
  method = "GET"
  timeout = "10s"
  path = "/health"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

[[vm]]
  memory = '256mb'
  cpus = 1

[[metrics]]
  port = 8080
  path = "/metrics"
